# Generated by Django 6.1 on 2026-08-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='response_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='response_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
