# Generated by Django 6.1 on 2026-08-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_alter_delivery_response_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='attempt_count',
            field=models.IntegerField(default=1),
        ),
    ]
