# Generated by Django 6.1 on 2026-08-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0006_deliveryattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DEAD_LETTERED', 'Dead Lettered')], default='PENDING', max_length=20),
        ),
    ]
