# Generated by Django 6.1 on 2026-08-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0007_alter_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='secret',
            field=models.CharField(default='dev-secret', max_length=255),
            preserve_default=False,
        ),
    ]
